/**
 * Auth Related Constants
 */

export const AUTH_MESSAGES = {
  FORGOT_PASSWORD: {
    TITLE: "Forgot your password?",
    DESCRIPTION: "Enter the email linked to your account and we'll send a reset link straight to your inbox.",
    EMAIL_LABEL: "Email address",
    EMAIL_PLACEHOLDER: "you@example.com",
    SUBMIT_BUTTON: "Send reset link",
    SUBMITTING_BUTTON: "Sending…",
    BACK_TO_SIGNIN: "Back to sign in",
    REMEMBER_PASSWORD: "Remember your password?",
    SIGNIN_LINK: "Sign in",
    GOOGLE_WARNING: "Signed up with Google? You don't have a password.",
    GOOGLE_SIGNIN_LINK: "Sign in with Google instead.",
    SENT_TITLE: "Check your inbox",
    SENT_DESCRIPTION: (email: string) => `If ${email} is linked to an account, we've sent a reset link. It expires in 1 hour.`,
    SENT_NOT_RECEIVED: "Didn't receive it?",
    SENT_SPAM_NOTICE: "Check your spam folder, or",
    SENT_TRY_AGAIN: "try again",
    SENT_GOOGLE_PROMPT: "Using Google?",
    SENT_GOOGLE_LINK: "Sign in with Google instead",
  },
  RESET_PASSWORD: {
    TITLE: "Set new password",
    DESCRIPTION: "Choose a strong password for your account.",
    PASSWORD_LABEL: "New password",
    PASSWORD_PLACEHOLDER: "At least 8 characters",
    CONFIRM_LABEL: "Confirm password",
    CONFIRM_PLACEHOLDER: "Re-enter new password",
    SUBMIT_BUTTON: "Update password",
    SUBMITTING_BUTTON: "Updating…",
    SUCCESS_TITLE: "Password updated!",
    SUCCESS_DESCRIPTION: "Your password has been changed. Redirecting you to sign in…",
    INVALID_TITLE: "Link expired or invalid",
    INVALID_DESCRIPTION: "This reset link has expired or already been used. Links are valid for 1 hour.",
    INVALID_BUTTON: "Request a new link",
    STRENGTH_WEAK: "Weak",
    STRENGTH_FAIR: "Fair",
    STRENGTH_GOOD: "Good",
    STRENGTH_STRONG: "Strong",
  },
  LOGIN: {
    TITLE: "Welcome back",
    DESCRIPTION: "Sign in to access your dashboard.",
    EMAIL_LABEL: "Email Address",
    EMAIL_PLACEHOLDER: "you@company.com",
    PASSWORD_LABEL: "Password",
    PASSWORD_PLACEHOLDER: "••••••••",
    FORGOT_PASSWORD: "Forgot password?",
    SUBMIT_BUTTON: "Sign In",
    SUBMITTING_BUTTON: "Signing in…",
    CREATE_ACCOUNT_PROMPT: "Don't have an account?",
    CREATE_ACCOUNT_LINK: "Create Account",
    GOOGLE_BUTTON: "Continue with Google",
    OR_CONTINUE: "or continue with",
    MAGIC_LINK_BUTTON: "Send magic link",
    MAGIC_LINK_SENT: "Check your inbox",
  },
  SIGNUP: {
    TITLE: "Create your account",
    DESCRIPTION: "Start generating content with AI in minutes.",
    NAME_LABEL: "Full Name",
    NAME_PLACEHOLDER: "Jane Doe",
    EMAIL_LABEL: "Email Address",
    EMAIL_PLACEHOLDER: "you@company.com",
    PASSWORD_LABEL: "Password",
    PASSWORD_PLACEHOLDER: "••••••••",
    SUBMIT_BUTTON: "Create Account",
    SUBMITTING_BUTTON: "Creating…",
    ALREADY_HAVE_ACCOUNT: "Already have an account?",
    SIGNIN_LINK: "Sign In",
    GOOGLE_BUTTON: "Continue with Google",
    OR_CONTINUE: "or continue with",
  },
} as const;
